# Generated by Django 5.0.2 on 2024-02-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='azamovshahboz06082001@gmail.com', max_length=254),
        ),
    ]
